### ISSUE TITLE
Add Time on X Axis

### ISSUE THREAD

**Issue by bad6e** [bad6e/credit_cards#123]
The only two points on the xaxis of the graph or the first/last date - can we add one in the middle?

**Comment by btthomas** [comment]
added the x-tick in the middle: 5ffabfd0bb49a52e60f86478c58dce894c8a8ac7
I also changed the label to 'date'.

Still need to customize the tooltip with the fields that need to be added to the rewards db and api.

**Comment by bad6e** [comment]
Thanks looks great
